apiVersion: iam.minio.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/user
  labels:
    testing.upbound.io/example-name: example-user
  name: example-user
spec:
  forProvider:
    forceDestroy: true
  providerConfigRef:
    name: default