apiVersion: iam.minio.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: example-service-account
spec:
  forProvider:
    targetUser: example-user
    description: "Service account for automated tasks"
  providerConfigRef:
    name: default