name: aminueza/minio
resources:
    minio_s3_bucket:
        subCategory: "S3"
        description: Manages a MinIO S3 bucket
        name: minio_s3_bucket
        title: minio_s3_bucket Resource - terraform-provider-minio
        examples: []
        argumentDocs: {}
        importStatements: []
    minio_s3_bucket_policy:
        subCategory: "S3"
        description: Manages a MinIO S3 bucket policy
        name: minio_s3_bucket_policy
        title: minio_s3_bucket_policy Resource - terraform-provider-minio
        examples: []
        argumentDocs: {}
        importStatements: []
    minio_s3_object:
        subCategory: "S3"
        description: Manages a MinIO S3 object
        name: minio_s3_object
        title: minio_s3_object Resource - terraform-provider-minio
        examples: []
        argumentDocs: {}
        importStatements: []
    minio_s3_bucket_versioning:
        subCategory: "S3"
        description: Manages MinIO S3 bucket versioning
        name: minio_s3_bucket_versioning
        title: minio_s3_bucket_versioning Resource - terraform-provider-minio
        examples: []
        argumentDocs: {}
        importStatements: []
    minio_s3_bucket_notification:
        subCategory: "S3"
        description: Manages MinIO S3 bucket notifications
        name: minio_s3_bucket_notification
        title: minio_s3_bucket_notification Resource - terraform-provider-minio
        examples: []
        argumentDocs: {}
        importStatements: []
    minio_iam_user:
        subCategory: "IAM"
        description: Manages a MinIO IAM user
        name: minio_iam_user
        title: minio_iam_user Resource - terraform-provider-minio
        examples: []
        argumentDocs: {}
        importStatements: []
    minio_iam_policy:
        subCategory: "IAM"
        description: Manages a MinIO IAM policy
        name: minio_iam_policy
        title: minio_iam_policy Resource - terraform-provider-minio
        examples: []
        argumentDocs: {}
        importStatements: []
    minio_iam_group:
        subCategory: "IAM"
        description: Manages a MinIO IAM group
        name: minio_iam_group
        title: minio_iam_group Resource - terraform-provider-minio
        examples: []
        argumentDocs: {}
        importStatements: []
    minio_iam_service_account:
        subCategory: "IAM"
        description: Manages a MinIO IAM service account
        name: minio_iam_service_account
        title: minio_iam_service_account Resource - terraform-provider-minio
        examples: []
        argumentDocs: {}
        importStatements: []
    minio_kms_key:
        subCategory: "KMS"
        description: Manages a MinIO KMS key
        name: minio_kms_key
        title: minio_kms_key Resource - terraform-provider-minio
        examples: []
        argumentDocs: {}
        importStatements: []