apiVersion: s3.minio.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: example-bucket
  name: example-bucket
spec:
  forProvider:
    bucket: example-crossplane-bucket
    acl: private
    forceDestroy: true
  providerConfigRef:
    name: default